services:
    was:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            -   ${SERVER_PORT}:${SERVER_PORT}
        depends_on:
            db:
                condition: service_healthy
        networks:
            - container-network

    db:
        image: mysql:9.2.0
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - mysqldata:/var/lib/mysql
        networks:
            - container-network
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
            timeout: 20s
            retries: 10

networks:
    container-network:
        driver: bridge

volumes:
    mysqldata:
