spring:
  application:
    name: backend

  config:
    import: classpath:private/dev_config.yml

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true